#!/usr/bin/env python3
"""
Send test execution summary notifications to Email and Google Chat
"""
import json
import sys
import os
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib

def send_email(summary_data, config):
    """Send email notification"""
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"Test Report: {config['project_name']} - {'✅ PASSED' if summary_data['failed'] == 0 else '❌ FAILED'}"
    msg['From'] = config['email_from']
    msg['To'] = ', '.join(config['email_to'])
    
    # Create HTML email body
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2>🧪 Test Execution Summary</h2>
        <h3>{config['project_name']}</h3>
        
        <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
            <tr style="background-color: #f2f2f2;">
                <th style="padding: 12px; text-align: left; border: 1px solid #ddd;">Metric</th>
                <th style="padding: 12px; text-align: left; border: 1px solid #ddd;">Count</th>
            </tr>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;">Total Tests</td>
                <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">{summary_data['total']}</td>
            </tr>
            <tr style="background-color: #d4edda;">
                <td style="padding: 12px; border: 1px solid #ddd;">Passed</td>
                <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold; color: green;">✅ {summary_data['passed']}</td>
            </tr>
            <tr style="background-color: #f8d7da;">
                <td style="padding: 12px; border: 1px solid #ddd;">Failed</td>
                <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold; color: red;">❌ {summary_data['failed']}</td>
            </tr>
            <tr style="background-color: #fff3cd;">
                <td style="padding: 12px; border: 1px solid #ddd;">Skipped</td>
                <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold; color: orange;">⏭️ {summary_data['skipped']}</td>
            </tr>
            <tr>
                <td style="padding: 12px; border: 1px solid #ddd;">Pass Rate</td>
                <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">{summary_data['pass_rate']}%</td>
            </tr>
        </table>
        
        <h3 style="margin-top: 30px;">📎 Links</h3>
        <ul style="list-style: none; padding: 0;">
            <li style="margin: 10px 0;"><strong>Build:</strong> <a href="{config['build_url']}">{config['build_url']}</a></li>
            <li style="margin: 10px 0;"><strong>Allure Report:</strong> <a href="{config['report_url']}">{config['report_url']}</a></li>
            <li style="margin: 10px 0;"><strong>Logs:</strong> <a href="{config['logs_url']}">{config['logs_url']}</a></li>
        </ul>
        
        <p style="color: #666; font-size: 12px; margin-top: 30px;">
            Generated by API Automation Framework
        </p>
    </body>
    </html>
    """
    
    msg.attach(MIMEText(html_body, 'html'))
    
    # Send email
    try:
        with smtplib.SMTP(config['smtp_host'], config['smtp_port']) as server:
            if config.get('smtp_use_tls', True):
                server.starttls()
            if config.get('smtp_username') and config.get('smtp_password'):
                server.login(config['smtp_username'], config['smtp_password'])
            server.send_message(msg)
        print("✅ Email sent successfully")
    except Exception as e:
        print(f"❌ Failed to send email: {e}", file=sys.stderr)

def send_google_chat(summary_data, config):
    """Send Google Chat notification via webhook with enhanced UI"""
    
    # Determine status and styling
    failed_count = summary_data['failed']
    pass_rate = float(summary_data['pass_rate'])
    
    if failed_count == 0:
        status_emoji = "🎉"
        status_text = "ALL TESTS PASSED"
        status_color = "#34A853"  # Green
        header_image = "https://img.icons8.com/color/96/000000/ok--v1.png"
    elif pass_rate >= 90:
        status_emoji = "⚠️"
        status_text = "MOSTLY PASSED"
        status_color = "#FBBC04"  # Yellow
        header_image = "https://img.icons8.com/color/96/000000/medium-risk.png"
    else:
        status_emoji = "❌"
        status_text = "TESTS FAILED"
        status_color = "#EA4335"  # Red
        header_image = "https://img.icons8.com/color/96/000000/high-risk.png"
    
    # Calculate execution time if available
    execution_time = summary_data.get('execution_time', 'N/A')
    
    # Create enhanced Google Chat card message
    message = {
        "cardsV2": [{
            "cardId": "test-report-card",
            "card": {
                "header": {
                    "title": f"{status_emoji} {config['project_name']}",
                    "subtitle": f"Status: {status_text}",
                    "imageUrl": header_image,
                    "imageType": "CIRCLE"
                },
                "sections": [
                    {
                        "header": "📊 Test Results Summary",
                        "collapsible": False,
                        "widgets": [
                            {
                                "decoratedText": {
                                    "topLabel": "Total Tests Executed",
                                    "text": f"<b>{summary_data['total']}</b>",
                                    "startIcon": {
                                        "knownIcon": "BOOKMARK"
                                    }
                                }
                            },
                            {
                                "decoratedText": {
                                    "topLabel": "Passed",
                                    "text": f"<font color='#34A853'><b>✅ {summary_data['passed']}</b></font>",
                                    "startIcon": {
                                        "knownIcon": "STAR"
                                    }
                                }
                            },
                            {
                                "decoratedText": {
                                    "topLabel": "Failed",
                                    "text": f"<font color='#EA4335'><b>❌ {summary_data['failed']}</b></font>",
                                    "startIcon": {
                                        "knownIcon": "DESCRIPTION"
                                    }
                                }
                            },
                            {
                                "decoratedText": {
                                    "topLabel": "Skipped",
                                    "text": f"<font color='#FBBC04'><b>⏭️ {summary_data['skipped']}</b></font>",
                                    "startIcon": {
                                        "knownIcon": "CLOCK"
                                    }
                                }
                            },
                            {
                                "divider": {}
                            },
                            {
                                "decoratedText": {
                                    "topLabel": "Pass Rate",
                                    "text": f"<font color='{status_color}'><b>{summary_data['pass_rate']}%</b></font>",
                                    "startIcon": {
                                        "knownIcon": "MULTIPLE_PEOPLE"
                                    }
                                }
                            }
                        ]
                    },
                    {
                        "header": "🔗 Quick Actions",
                        "collapsible": False,
                        "widgets": [
                            {
                                "buttonList": {
                                    "buttons": [
                                        {
                                            "text": "📊 View Report",
                                            "onClick": {
                                                "openLink": {
                                                    "url": config['report_url']
                                                }
                                            }
                                        },
                                        {
                                            "text": "🔧 Jenkins Build",
                                            "onClick": {
                                                "openLink": {
                                                    "url": config['build_url']
                                                }
                                            }
                                        },
                                        {
                                            "text": "📋 View Logs",
                                            "onClick": {
                                                "openLink": {
                                                    "url": config['logs_url']
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }
        }]
    }
    
    # Send to Google Chat webhook
    try:
        response = requests.post(
            config['google_chat_webhook'],
            json=message,
            headers={'Content-Type': 'application/json; charset=UTF-8'}
        )
        response.raise_for_status()
        print("✅ Google Chat notification sent successfully")
    except Exception as e:
        print(f"❌ Failed to send Google Chat notification: {e}", file=sys.stderr)

def main():
    if len(sys.argv) < 3:
        print("Usage: python send-notification.py <summary-json> <config-json>")
        sys.exit(1)
    
    summary_file = sys.argv[1]
    config_file = sys.argv[2]
    
    # Load summary data
    with open(summary_file, 'r') as f:
        summary_data = json.load(f)
    
    # Load config
    with open(config_file, 'r') as f:
        config = json.load(f)
    
    # Send notifications
    if config.get('enable_email', False):
        send_email(summary_data, config)
    
    if config.get('enable_google_chat', False):
        send_google_chat(summary_data, config)

if __name__ == '__main__':
    main()
